apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gmora.fullname" . }}-worker
  labels:
    {{- include "gmora.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.autoscaling.worker.enabled }}
  replicas: {{ .Values.replicaCount.worker }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gmora.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "gmora.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "gmora.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["worker"]
          env:
            - name: APP_ROLE
              value: worker
            - name: RUN_MIGRATIONS
              value: "false"
            {{- include "gmora.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
