{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gmora.fullname" . }}-secrets
  labels:
    {{- include "gmora.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ required "secrets.APP_KEY is required" .Values.secrets.APP_KEY | quote }}
  DB_PASSWORD: {{ required "secrets.DB_PASSWORD is required" .Values.secrets.DB_PASSWORD | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | default "" | quote }}
  AWS_ACCESS_KEY_ID: {{ required "secrets.AWS_ACCESS_KEY_ID is required" .Values.secrets.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "secrets.AWS_SECRET_ACCESS_KEY is required" .Values.secrets.AWS_SECRET_ACCESS_KEY | quote }}
{{- end }}
